"use client"
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css';
import {Navbar} from "./components/navbar/Navbar";
import Loader from './components/loader/loader';
import { LoaderContext, LoaderProvider } from './context/loaderContext';
import { useContext } from 'react';


const inter = Inter({ subsets: ['latin'] })

 const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const loadingContext  = useContext(LoaderContext)
  console.log(loadingContext, "// @ts-ignore: Ignoring this error for demonstration purposes");
  
  return (
    <html lang="en">
      <head>
      <link href="https://cdn.jsdelivr.net/npm/remixicon@3.2.0/fonts/remixicon.css" rel="stylesheet"/>
      </head>
      <body className={inter.className}>
        <LoaderProvider>
          <Loader/>
        <Navbar/>
        {children}
        </LoaderProvider>
        </body>
    </html>
  )
}
